#!/usr/bin/env python3
"""Hermes collector tests (Phase 2 Task 2).

Runs offline against the sanitized fixture databases under
``tests/fixtures/hermes-profiles`` (generated by
``tests/make_hermes_fixtures.py``). Never touches the live Hermes
installation, the network or any real account data.

Timestamps are asserted under a fixed machine timezone so the tests are
stable regardless of where they run:

    TZ=America/Guayaquil python3 -m unittest discover -s tests -p 'test_*.py' -v
"""

import json
import os
import shutil
import sqlite3
import subprocess
import sys
import tempfile
import unittest
from importlib.machinery import SourceFileLoader
from importlib.util import module_from_spec, spec_from_loader
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "scripts" / "agent-fleet-hermes"
FIXTURES = ROOT / "tests" / "fixtures" / "hermes-profiles"

_LOADER = SourceFileLoader("agent_fleet_hermes", str(SCRIPT))
collector = module_from_spec(spec_from_loader(_LOADER.name, _LOADER))
_LOADER.exec_module(collector)

# America/Guayaquil is UTC-5 year round: 1790219027.6 -> 2026-09-23T22:03:47-05:00
TIMES = {
    "s1_last": "2026-09-23T22:03:47-05:00",      # 1790219027.6
    "s2_last": "2026-09-26T13:06:29-05:00",      # 1790445989.0
    "scribe_message": "2026-09-26T22:33:20-05:00",  # 1790480000.0
}

RECORD_KEYS = {
    "timestamp", "harness", "agent", "provider", "model", "sessionId",
    "task", "calls", "inputTokens", "outputTokens", "cacheReadTokens",
    "cacheWriteTokens",
}
PROFILE_KEYS = {"agent", "displayName", "records", "error"}


def run_collect(*extra):
    env = dict(os.environ, TZ="America/Guayaquil")
    proc = subprocess.run(
        [sys.executable, str(SCRIPT), *extra],
        capture_output=True, text=True, timeout=30, env=env,
    )
    assert proc.returncode == 0, f"exit {proc.returncode}: {proc.stderr}"
    return json.loads(proc.stdout)


def profile(record, agent):
    for entry in record["profiles"]:
        if entry["agent"] == agent:
            return entry
    raise AssertionError(f"profile {agent!r} missing from {record['profiles']}")


def find(records, **where):
    matches = [r for r in records if all(r.get(k) == v for k, v in where.items())]
    if len(matches) != 1:
        raise AssertionError(f"expected exactly one record matching {where}, got {matches}")
    return matches[0]


class ContractShapeTest(unittest.TestCase):
    def setUp(self):
        self.record = run_collect("--root", str(FIXTURES))

    def test_envelope(self):
        self.assertEqual(set(self.record), {"schemaVersion", "provider", "available", "profiles", "error"})
        self.assertEqual(self.record["schemaVersion"], 1)
        self.assertEqual(self.record["provider"], "hermes")
        self.assertTrue(self.record["available"])
        self.assertIsNone(self.record["error"])

    def test_profiles_are_sorted_and_all_fixture_profiles_present(self):
        self.assertEqual([p["agent"] for p in self.record["profiles"]],
                         ["diana", "engineer", "oracle", "scribe"])
        for p in self.record["profiles"]:
            self.assertEqual(set(p), PROFILE_KEYS)

    def test_every_record_matches_usage_record_contract(self):
        for p in self.record["profiles"]:
            for r in p["records"]:
                self.assertEqual(set(r), RECORD_KEYS, "record keys drifted")
                self.assertEqual(r["harness"], "hermes")
                self.assertEqual(r["provider"], "openai-codex")
                self.assertEqual(r["agent"], p["agent"])
                for key in ("calls", "inputTokens", "outputTokens",
                            "cacheReadTokens", "cacheWriteTokens"):
                    self.assertIsInstance(r[key], int, key)
                    self.assertGreaterEqual(r[key], 0)

    def test_stdout_is_exactly_one_json_document(self):
        env = dict(os.environ, TZ="America/Guayaquil")
        proc = subprocess.run(
            [sys.executable, str(SCRIPT), "--root", str(FIXTURES)],
            capture_output=True, text=True, env=env)
        self.assertEqual(proc.stdout.count("\n"), 1, "stdout must be a single JSON document")
        json.loads(proc.stdout)


class AggregationSemanticsTest(unittest.TestCase):
    """The core Phase 2 refinement: rows are aggregates, never per-call events."""

    def setUp(self):
        self.engineer = profile(run_collect("--root", str(FIXTURES)), "engineer")

    def test_one_record_per_usage_row_not_per_call(self):
        # The 20260923 session has 7+2+3+1 = 13 codex calls across 4 source
        # rows: expect exactly 4 records, each keeping its own ``calls`` count.
        records = [r for r in self.engineer["records"]
                   if r["sessionId"] == "20260923_180209_5d2a01"]
        self.assertEqual(len(records), 4)
        calls_by_task = {r["task"]: r["calls"] for r in records}
        self.assertEqual(calls_by_task, {"": 7, "approval": 2,
                                         "background_review": 3, "title_generation": 1})

    def test_no_record_is_fabricated_per_call(self):
        # Every record's ``calls`` comes from the source row; the sum of the
        # emitted counts equals the sum of the source rows, not N events.
        total = sum(r["calls"] for r in self.engineer["records"])
        self.assertEqual(total, 7 + 2 + 3 + 1 + 1 + 0)


class TaskBucketTest(unittest.TestCase):
    def setUp(self):
        self.engineer = profile(
            run_collect("--root", str(FIXTURES)), "engineer")

    def test_all_task_buckets_included(self):
        self.assertEqual({r["task"] for r in self.engineer["records"]},
                         {"", "approval", "background_review", "title_generation"})

    def test_task_is_kept_verbatim_for_all_including_empty_main_turn(self):
        record = find(self.engineer["records"],
                      sessionId="20260923_180209_5d2a01", model="gpt-6-astra",
                      task="")
        self.assertEqual(record["calls"], 7)

    def test_task_kept_for_internal_use_not_displayed(self):
        # The field is present and stable; nothing rewrites or localizes it.
        for r in self.engineer["records"]:
            self.assertIsInstance(r["task"], str)


class ProviderFilterTest(unittest.TestCase):
    def setUp(self):
        self.engineer = profile(
            run_collect("--root", str(FIXTURES)), "engineer")

    def test_only_openai_codex_records_surface(self):
        for r in self.engineer["records"]:
            self.assertEqual(r["provider"], "openai-codex")

    def test_non_codex_models_never_surface(self):
        models = {r["model"] for r in self.engineer["records"]}
        self.assertNotIn("grok-4.7", models)
        self.assertNotIn("qwen3.6:35b", models)
        self.assertEqual(models, {"gpt-6-astra", "gpt-5.5", "gpt-6-sol"})

    def test_profile_without_any_codex_usage_is_present_but_empty(self):
        diana = profile(run_collect("--root", str(FIXTURES)), "diana")
        self.assertEqual(diana["records"], [])
        self.assertIsNone(diana["error"])


class TimestampSemanticsTest(unittest.TestCase):
    def setUp(self):
        root = run_collect("--root", str(FIXTURES))
        self.engineer = profile(root, "engineer")
        self.oracle = profile(root, "oracle")
        self.scribe = profile(root, "scribe")

    def test_session_last_activity_maps_to_iso8601_local(self):
        record = find(self.engineer["records"],
                      sessionId="20260923_180209_5d2a01", task="")
        self.assertEqual(record["timestamp"], TIMES["s1_last"])

    def test_missing_timestamp_is_null_never_invented(self):
        record = find(self.oracle["records"], sessionId="20260923_180209_000orx")
        self.assertIsNone(record["timestamp"])
        # but the usage itself is real and must survive with all counters
        self.assertEqual((record["calls"], record["inputTokens"]), (4, 30210))

    def test_message_timestamp_is_the_fallback(self):
        record = self.scribe["records"][0]
        self.assertEqual(record["timestamp"], TIMES["scribe_message"])


class DisplayIdentityTest(unittest.TestCase):
    def setUp(self):
        self.engineer = profile(
            run_collect("--root", str(FIXTURES)), "engineer")
        self.diana = profile(
            run_collect("--root", str(FIXTURES)), "diana")

    def test_profile_yaml_title_used_when_present(self):
        self.assertEqual(self.engineer["displayName"], "Engineer")

    def test_empty_profile_yaml_falls_back_to_null(self):
        self.assertIsNone(self.diana["displayName"])

    def test_agent_is_the_directory_name(self):
        self.assertEqual(self.engineer["agent"], "engineer")


class ZeroAndNullSemanticsTest(unittest.TestCase):
    def setUp(self):
        self.engineer = profile(
            run_collect("--root", str(FIXTURES)), "engineer")

    def test_zero_counters_are_values(self):
        record = find(self.engineer["records"],
                      sessionId="20260924_202338_a91b77", model="gpt-5.5")
        self.assertEqual(record["calls"], 0)
        self.assertEqual(record["inputTokens"], 0)
        self.assertEqual(record["outputTokens"], 0)
        self.assertEqual(record["cacheReadTokens"], 0)
        self.assertEqual(record["cacheWriteTokens"], 0)

    def test_unit_helpers_reject_junk(self):
        self.assertEqual(collector.non_negative_int(None), 0)
        self.assertEqual(collector.non_negative_int("-5"), 0)
        self.assertEqual(collector.non_negative_int(-3), 0)
        self.assertEqual(collector.non_negative_int(42), 42)
        self.assertEqual(collector.non_negative_int(42.9), 42)
        self.assertIsNone(collector.iso_timestamp(None))
        self.assertIsNone(collector.iso_timestamp(0))
        self.assertIsNone(collector.iso_timestamp("junk"))
        self.assertIsNotNone(collector.iso_timestamp(1790186529.0))


class FailureModeTest(unittest.TestCase):
    def test_missing_profiles_root_yields_unavailable_record(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp) / "does-not-exist"
            record = run_collect("--root", str(root))
            self.assertFalse(record["available"])
            self.assertEqual(record["profiles"], [])
            self.assertIsNone(record["error"])

    def test_corrupt_database_is_isolated_per_profile(self):
        with tempfile.TemporaryDirectory() as tmp:
            broken_dir = Path(tmp) / "broken"
            broken_dir.mkdir()
            (broken_dir / "state.db").write_bytes(b"not a sqlite database at all")
            healthy_dir = Path(tmp) / "healthy"
            healthy_dir.mkdir()
            shutil.copy(FIXTURES / "engineer" / "state.db", healthy_dir / "state.db")

            env = dict(os.environ, TZ="America/Guayaquil")
            proc = subprocess.run(
                [sys.executable, str(SCRIPT), "--root", tmp],
                capture_output=True, text=True, env=env)
            self.assertEqual(proc.returncode, 0)
            record = json.loads(proc.stdout)

            broken = record["profiles"][0]
            self.assertEqual(broken["agent"], "broken")
            self.assertEqual(broken["records"], [])
            self.assertIsNotNone(broken["error"])
            self.assertTrue(broken["error"]["message"])

            healthy = record["profiles"][1]
            self.assertEqual(healthy["agent"], "healthy")
            self.assertEqual(len(healthy["records"]), 6)
            self.assertIsNone(healthy["error"])

    def test_profile_without_state_db_is_reported_not_fatal(self):
        with tempfile.TemporaryDirectory() as tmp:
            (Path(tmp) / "empty-profile").mkdir()
            record = run_collect("--root", tmp)
            entry = record["profiles"][0]
            self.assertEqual(entry["agent"], "empty-profile")
            self.assertEqual(entry["records"], [])
            self.assertIsNotNone(entry["error"])


class DeterminismTest(unittest.TestCase):
    def test_same_input_same_output(self):
        first = run_collect("--root", str(FIXTURES))
        second = run_collect("--root", str(FIXTURES))
        self.assertEqual(json.dumps(first, sort_keys=True),
                         json.dumps(second, sort_keys=True))


if __name__ == "__main__":
    unittest.main()
