#!/usr/bin/env python3
"""Hermes collector tests (Phase 2 Task 3).

Runs offline against the sanitized fixture databases under
``tests/fixtures/hermes-profiles`` (generated by
``tests/make_hermes_fixtures.py``). Never touches the live Hermes
installation, the network or any real account data.

Every run pins ``--now`` to a fixture epoch so the 7-day lookback is
deterministic, and sets a fixed machine timezone so the ISO timestamps are
stable regardless of where the suite runs:

    TZ=America/Guayaquil python3 -m unittest discover -s tests -p 'test_*.py' -v
"""

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from importlib.machinery import SourceFileLoader
from importlib.util import module_from_spec, spec_from_loader
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "scripts" / "agent-fleet-hermes"
FIXTURES = ROOT / "tests" / "fixtures" / "hermes-profiles"

_LOADER = SourceFileLoader("agent_fleet_hermes", str(SCRIPT))
collector = module_from_spec(spec_from_loader(_LOADER.name, _LOADER))
_LOADER.exec_module(collector)

# Fixture epochs (see tests/make_hermes_fixtures.py); the newest known
# timestamp in the tree.
S1_LAST = 1790219027.6      # engineer gpt-6-astra session (2026-09-23)
S2_LAST = 1790445989.0      # engineer gpt-6-sol / gpt-5.5 session (2026-09-26)
SCRIBE = 1790480000.0       # scribe, message fallback (2026-09-26)

TIMES = {
    "s1_last": "2026-09-23T22:03:47-05:00",
    "s2_last": "2026-09-26T13:06:29-05:00",
    "scribe": "2026-09-26T22:33:20-05:00",
}


def run_collect(*extra):
    env = dict(os.environ, TZ="America/Guayaquil")
    proc = subprocess.run(
        [sys.executable, str(SCRIPT), *extra],
        capture_output=True, text=True, timeout=30, env=env,
    )
    assert proc.returncode == 0, f"exit {proc.returncode}: {proc.stderr}"
    return json.loads(proc.stdout)


def full_run():
    """Deterministic run where every fixture record is inside the window."""
    return run_collect("--root", str(FIXTURES), "--lookback-days", "7",
                       "--now", str(SCRIBE))


def agent(record, agent_id):
    for entry in record["agents"]:
        if entry["id"] == agent_id:
            return entry
    raise AssertionError(f"agent {agent_id!r} missing (have {[a['id'] for a in record['agents']]})")


def model(entry, name):
    matches = [m for m in entry["models"] if m["model"] == name]
    if len(matches) != 1:
        raise AssertionError(f"expected exactly one model {name!r}, got {entry['models']}")
    return matches[0]


MODEL_KEYS = {"provider", "model", "calls", "inputTokens", "outputTokens",
              "cacheReadTokens", "cacheWriteTokens", "lastActivityAt"}
AGENT_KEYS = {"id", "displayName", "models", "totalCalls", "lastActivityAt", "error"}


class ContractShapeTest(unittest.TestCase):
    def setUp(self):
        self.record = full_run()

    def test_envelope_matches_phase_two_summary_contract(self):
        self.assertEqual(set(self.record),
                         {"schemaVersion", "harness", "available", "source",
                          "agents", "summary", "error"})
        self.assertEqual(self.record["schemaVersion"], 1)
        self.assertEqual(self.record["harness"], "hermes")
        self.assertTrue(self.record["available"])
        self.assertEqual(self.record["source"],
                         {"type": "local", "profilesDiscovered": 4})
        self.assertEqual(set(self.record["summary"]), {"totalAgents", "totalCalls"})
        self.assertIsNone(self.record["error"])

    def test_agents_are_sorted_and_every_fixture_profile_present(self):
        self.assertEqual([a["id"] for a in self.record["agents"]],
                         ["diana", "engineer", "oracle", "scribe"])
        for entry in self.record["agents"]:
            self.assertEqual(set(entry), AGENT_KEYS)
            for m in entry["models"]:
                self.assertEqual(set(m), MODEL_KEYS)
                self.assertEqual(m["provider"], "openai-codex")
                for key in ("calls", "inputTokens", "outputTokens",
                            "cacheReadTokens", "cacheWriteTokens"):
                    self.assertIsInstance(m[key], int, key)
                    self.assertGreaterEqual(m[key], 0)

    def test_contract_fields_are_activity_only_no_allowance_math(self):
        # No share/percent/attribution surface exists anywhere in the tree.
        text = json.dumps(self.record)
        for forbidden in ("percent", "share", "allowance", "attribution"):
            self.assertNotIn(forbidden, text)

    def test_stdout_is_exactly_one_json_document(self):
        env = dict(os.environ, TZ="America/Guayaquil")
        proc = subprocess.run(
            [sys.executable, str(SCRIPT), "--root", str(FIXTURES),
             "--now", str(SCRIBE)],
            capture_output=True, text=True, env=env)
        self.assertEqual(proc.stdout.count("\n"), 1, "stdout must be a single JSON document")
        json.loads(proc.stdout)


class AggregationSemanticsTest(unittest.TestCase):
    """Rows are aggregates; four source rows fold into one model entry.

    Repeated calls to the same model/session sum instead of fanning out
    into per-call events.
    """

    def setUp(self):
        self.engineer = agent(full_run(), "engineer")

    def test_repeated_calls_fold_into_one_model_entry(self):
        astra = model(self.engineer, "gpt-6-astra")
        # 20260923 session: 7 + 2 + 3 + 1 calls across 4 source rows.
        self.assertEqual(astra["calls"], 13)
        self.assertEqual(astra["inputTokens"], 45897 + 1018 + 4740 + 281)
        self.assertEqual(astra["outputTokens"], 2360 + 14 + 354 + 14)
        self.assertEqual(astra["cacheReadTokens"], 168960 + 86912)
        self.assertEqual(astra["cacheWriteTokens"], 0)

    def test_no_per_call_fabrication_totals_match_source_rows(self):
        engineer_calls = self.engineer["totalCalls"]
        # 13 (astra) + 1 (sol) + 0 (gpt-5.5 row) -- row counts, not 15 events.
        self.assertEqual(engineer_calls, 14)

    def test_models_sorted_busiest_first_then_name(self):
        self.assertEqual([m["model"] for m in self.engineer["models"]],
                         ["gpt-6-astra", "gpt-6-sol", "gpt-5.5"])

    def test_zero_call_row_still_a_model_entry(self):
        g55 = model(self.engineer, "gpt-5.5")
        self.assertEqual(g55["calls"], 0)
        self.assertEqual(g55["inputTokens"], 0)
        self.assertIsNotNone(g55["lastActivityAt"])


class MultiAgentMultiModelTest(unittest.TestCase):
    def setUp(self):
        self.record = full_run()

    def test_multiple_agents(self):
        active = [a["id"] for a in self.record["agents"] if a["totalCalls"] > 0]
        self.assertEqual(active, ["engineer", "oracle", "scribe"])

    def test_multiple_models_per_agent(self):
        self.assertEqual(len(agent(self.record, "engineer")["models"]), 3)

    def test_same_model_under_different_agents_is_separate(self):
        by_agent = {
            a["id"]: [m for m in a["models"] if m["model"] == "gpt-6-sol"]
            for a in self.record["agents"]
        }
        self.assertEqual(by_agent["engineer"][0]["calls"], 1)
        self.assertEqual(by_agent["scribe"][0]["calls"], 2)


class LastActivityOrderingTest(unittest.TestCase):
    def setUp(self):
        self.record = full_run()
        self.engineer = agent(self.record, "engineer")

    def test_model_lastActivityIsMaxKnownTimestamp(self):
        self.assertEqual(model(self.engineer, "gpt-6-astra")["lastActivityAt"],
                         TIMES["s1_last"])
        self.assertEqual(model(self.engineer, "gpt-6-sol")["lastActivityAt"],
                         TIMES["s2_last"])

    def test_agent_lastActivityIsMaxAcrossModels(self):
        self.assertEqual(self.engineer["lastActivityAt"], TIMES["s2_last"])

    def test_null_timestamp_does_not_move_lastActivity(self):
        oracle = agent(self.record, "oracle")
        # oracle has real usage (4 calls) but no usable timestamp anywhere.
        self.assertEqual(oracle["totalCalls"], 4)
        self.assertIsNone(oracle["models"][0]["lastActivityAt"])
        self.assertIsNone(oracle["lastActivityAt"])

    def test_message_fallback_timestamp_is_last_resort(self):
        scribe = agent(self.record, "scribe")
        self.assertEqual(scribe["lastActivityAt"], TIMES["scribe"])

    def test_zero_activity_agent_has_null_lastActivity(self):
        diana = agent(self.record, "diana")
        self.assertIsNone(diana["lastActivityAt"])


class SummaryCountsTest(unittest.TestCase):
    def setUp(self):
        self.record = full_run()

    def test_summary_totals(self):
        self.assertEqual(self.record["summary"], {"totalAgents": 3, "totalCalls": 20})

    def test_profiles_with_zero_activity_are_present_not_in_summary(self):
        diana = agent(self.record, "diana")
        self.assertEqual(diana["models"], [])
        self.assertEqual(diana["totalCalls"], 0)
        self.assertIsNone(diana["error"])
        # diana was discovered, not counted as active.
        self.assertEqual(self.record["source"]["profilesDiscovered"], 4)
        self.assertEqual(self.record["summary"]["totalAgents"], 3)


class ProviderFilterTest(unittest.TestCase):
    def setUp(self):
        self.record = full_run()

    def test_only_openai_codex_surfaces(self):
        for entry in self.record["agents"]:
            for m in entry["models"]:
                self.assertEqual(m["provider"], "openai-codex")

    def test_non_codex_models_never_surface(self):
        models = {m["model"] for a in self.record["agents"] for m in a["models"]}
        self.assertNotIn("grok-4.7", models)
        self.assertNotIn("qwen3.6:35b", models)
        self.assertNotIn("gpt-5.5-copilot", models)


class TaskPreservedInternallyTest(unittest.TestCase):
    def test_internal_records_keep_task_verbatim(self):
        # Task is no longer in the summary contract, but must still be
        # preserved on the internal normalized event for Phase 3.
        records = collector.load_profile(FIXTURES / "engineer")
        self.assertEqual(
            {(r["sessionId"], r["task"]) for r in records if r["model"] == "gpt-6-astra"},
            {("20260923_180209_5d2a01", ""),
             ("20260923_180209_5d2a01", "approval"),
             ("20260923_180209_5d2a01", "background_review"),
             ("20260923_180209_5d2a01", "title_generation")})

    def test_task_is_not_leaked_into_the_summary_contract(self):
        text = json.dumps(full_run())
        self.assertIsNone(re.search(r'"task"\s*:', text))

    def test_internal_timestamp_is_epoch_not_iso(self):
        records = collector.load_profile(FIXTURES / "engineer")
        for record in records:
            if record["timestamp"] is not None:
                self.assertIsInstance(record["timestamp"], float)


class DisplayIdentityTest(unittest.TestCase):
    def setUp(self):
        self.record = full_run()

    def test_profile_yaml_title_used_when_present(self):
        self.assertEqual(agent(self.record, "engineer")["displayName"], "Engineer")

    def test_empty_profile_yaml_falls_back_to_directory_name(self):
        self.assertEqual(agent(self.record, "diana")["displayName"], "diana")


class LookbackTest(unittest.TestCase):
    """The 7-day window and its null-timestamp policy."""

    def test_default_lookback_is_seven_days(self):
        self.assertEqual(collector.DEFAULT_LOOKBACK_DAYS, 7.0)
        # The pinned now is 7 days after the oldest fixture record, so the
        # default window keeps the whole tree.
        cutoff = SCRIBE - 7.0 * 86400
        self.assertGreaterEqual(S1_LAST, cutoff)
        record = collector.collect(FIXTURES, collector.DEFAULT_LOOKBACK_DAYS, SCRIBE)
        self.assertEqual(record["summary"]["totalCalls"], 20)

    def test_records_outside_window_are_dropped(self):
        # now is after astra but before the later sessions; a 1-day window
        # keeps s2 (1790445989) and scribe (1790480000), drops astra.
        record = run_collect("--root", str(FIXTURES), "--lookback-days", "1",
                             "--now", "1790350000")
        engineer = agent(record, "engineer")
        self.assertEqual([m["model"] for m in engineer["models"]],
                         ["gpt-6-sol", "gpt-5.5"])
        self.assertEqual(engineer["totalCalls"], 1)
        self.assertEqual(agent(record, "scribe")["totalCalls"], 2)

    def test_null_timestamp_records_survive_any_window(self):
        # A window that would drop every known timestamp still keeps the
        # oracle rows because their timestamp is unknown.
        record = run_collect("--root", str(FIXTURES), "--lookback-days", "0",
                             "--now", str(int(S1_LAST + 1)))
        oracle = agent(record, "oracle")
        self.assertEqual(oracle["totalCalls"], 4)
        self.assertEqual(oracle["models"][0]["inputTokens"], 30210)

    def test_boundary_inclusion_at_cutoff(self):
        # cutoff == S1_LAST exactly: records AT the cutoff are included.
        record = run_collect("--root", str(FIXTURES), "--lookback-days", "1",
                             "--now", str(S1_LAST + 86400))
        engineer = agent(record, "engineer")
        astra = model(engineer, "gpt-6-astra")
        self.assertEqual(astra["calls"], 13)
        self.assertEqual(astra["lastActivityAt"], TIMES["s1_last"])

    def test_lookback_does_not_filter_profiles_out(self):
        # Even when a profile is fully outside the window it stays listed,
        # zeroed, so the UI can show "discovered but quiet".
        record = run_collect("--root", str(FIXTURES), "--lookback-days", "1",
                             "--now", "1790350000")
        ids = [a["id"] for a in record["agents"]]
        self.assertEqual(ids, ["diana", "engineer", "oracle", "scribe"])
        self.assertEqual(record["source"]["profilesDiscovered"], 4)


class FailureModeTest(unittest.TestCase):
    def test_missing_profiles_root_yields_unavailable_record(self):
        with tempfile.TemporaryDirectory() as tmp:
            record = run_collect("--root", str(Path(tmp) / "does-not-exist"))
            self.assertFalse(record["available"])
            self.assertEqual(record["source"], {"type": "local", "profilesDiscovered": 0})
            self.assertEqual(record["agents"], [])
            self.assertEqual(record["summary"], {"totalAgents": 0, "totalCalls": 0})
            self.assertEqual(record["error"]["code"], "HERMES_UNAVAILABLE")
            self.assertTrue(record["error"]["message"])

    def test_empty_profiles_root_is_available_but_quiet(self):
        with tempfile.TemporaryDirectory() as tmp:
            record = run_collect("--root", tmp)
            self.assertTrue(record["available"])
            self.assertEqual(record["agents"], [])
            self.assertEqual(record["source"]["profilesDiscovered"], 0)
            self.assertIsNone(record["error"])

    def test_corrupt_database_is_isolated_per_profile(self):
        with tempfile.TemporaryDirectory() as tmp:
            broken_dir = Path(tmp) / "broken"
            broken_dir.mkdir()
            (broken_dir / "state.db").write_bytes(b"not a sqlite database at all")
            healthy_dir = Path(tmp) / "healthy"
            healthy_dir.mkdir()
            shutil.copy(FIXTURES / "engineer" / "state.db", healthy_dir / "state.db")
            shutil.copy(FIXTURES / "engineer" / "profile.yaml", healthy_dir / "profile.yaml")

            env = dict(os.environ, TZ="America/Guayaquil")
            proc = subprocess.run(
                [sys.executable, str(SCRIPT), "--root", tmp, "--now", str(SCRIBE)],
                capture_output=True, text=True, env=env)
            self.assertEqual(proc.returncode, 0)
            record = json.loads(proc.stdout)

            self.assertTrue(record["available"])
            broken = agent(record, "broken")
            self.assertEqual(broken["models"], [])
            self.assertEqual(broken["totalCalls"], 0)
            self.assertEqual(broken["error"]["code"], "HERMES_PROFILE_UNREADABLE")
            self.assertTrue(broken["error"]["message"])
            self.assertNotIn(str(tmp), json.dumps(record["agents"]),
                             "no local paths leak into the agent entries")

            healthy = agent(record, "healthy")
            self.assertEqual(healthy["totalCalls"], 14)
            self.assertEqual(len(healthy["models"]), 3)
            self.assertIsNone(healthy["error"])

    def test_profile_without_state_db_is_reported_not_fatal(self):
        with tempfile.TemporaryDirectory() as tmp:
            (Path(tmp) / "empty-profile").mkdir()
            record = run_collect("--root", tmp)
            entry = agent(record, "empty-profile")
            self.assertEqual(entry["models"], [])
            self.assertEqual(entry["totalCalls"], 0)
            self.assertIsNotNone(entry["error"])


class UnitHelpersTest(unittest.TestCase):
    def test_non_negative_int_rejects_junk(self):
        self.assertEqual(collector.non_negative_int(None), 0)
        self.assertEqual(collector.non_negative_int("-5"), 0)
        self.assertEqual(collector.non_negative_int(-3), 0)
        self.assertEqual(collector.non_negative_int(42), 42)
        self.assertEqual(collector.non_negative_int(42.9), 42)

    def test_iso_timestamp_never_invents(self):
        self.assertIsNone(collector.iso_timestamp(None))
        self.assertIsNone(collector.iso_timestamp(0))
        self.assertIsNone(collector.iso_timestamp("junk"))
        self.assertIsNotNone(collector.iso_timestamp(1790186529.0))
        self.assertIsNone(collector.epoch_seconds(True))
        self.assertEqual(collector.epoch_seconds(1790186529.0), 1790186529.0)


class DeterminismTest(unittest.TestCase):
    def test_same_input_same_output(self):
        first = full_run()
        second = full_run()
        self.assertEqual(json.dumps(first, sort_keys=True),
                         json.dumps(second, sort_keys=True))


if __name__ == "__main__":
    unittest.main()
